name: statescope
description: Simple & performant state management using [InheritedNotifier].
version: 2.0.1
repository: "https://github.com/1l0/statescope"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
