name: simple_state_management
description: A Flutter package providing simple & performant state management using [InheritedNotifier].
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
