name: statescope
description: A Flutter package providing simple & performant state management using [InheritedNotifier].
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.4.0-282.3.beta

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
